name: Scheduled YouTube Videos Cleanup

on:
  schedule:
    # Run every Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run YouTube Videos Cleanup
      env:
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        chmod +x scripts/scheduled-cleanup.sh
        ./scripts/scheduled-cleanup.sh
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'YouTube Videos Cleanup Failed',
            body: `The scheduled YouTube videos cleanup failed on ${new Date().toISOString()}. Please check the logs for details.`
          }) 